config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Read all instances
  get '/tasks', to: 'tasks#index'
  # Read one instance
  get '/tasks/new', to: 'tasks#new'

  post '/tasks', to: 'tasks#create'

  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task

  patch '/tasks/:id', to: 'tasks#update'

  get '/tasks/:id', to: 'tasks#show', as: :task
  # Create new instance
  # Update one instance
  # Delete one instance
  delete '/tasks/:id', to: 'tasks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show

  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to task_path(@task)
  end

  def edit

  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    return params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<p>Completed: <%= @task.completed %></p>


<%= form_for @task do |f| %>
  <%= f.label :title  %>
  <%= f.text_field :title  %>

  <%= f.label :details  %>
  <%= f.text_field :details  %>

  <%= f.label :completed  %>
  <%= f.check_box :completed  %>

  <%= f.label :Submit  %>
  <%= f.submit  %>
<% end %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>

<ul>
  <% @tasks.each do |t| %>
    <li>
      <%= link_to t.title, task_path(t) %> -- <%= t.details %>. (<%= t.completed %>).
    </li>
  <% end  %>
</ul>

<%= link_to 'Create new Task', tasks_new_path %>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title  %>
  <%= f.text_field :title  %>

  <%= f.label :details  %>
  <%= f.text_field :details  %>

  <%= f.label :completed  %>
  <%= f.check_box :completed  %>

  <%= f.label :Submit  %>
  <%= f.submit  %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<p>Completed: <%= @task.completed %></p>
<%= link_to 'Edit', edit_task_path %>
<%= link_to 'Show all', tasks_path %>
<%= button_to 'Delete', task_path, method:'delete', data: {confirm: 'Are you sure?'} %>